// This file was generated by a python script

#ifndef component_list_hpp
#define component_list_hpp

#include <Simpleton/Utils/type list.hpp>

#include "sound component.hpp"
#include "unit dir component.hpp"
#include "position component.hpp"
#include "unit path component.hpp"
#include "unit stats component.hpp"
#include "tower shoot component.hpp"
#include "slow effect component.hpp"
#include "unit sprite component.hpp"
#include "tower effect component.hpp"
#include "tower timing component.hpp"
#include "tower target component.hpp"
#include "turret tower component.hpp"
#include "splash tower component.hpp"
#include "tower sprites component.hpp"
#include "poison effect component.hpp"
#include "tower upgrades component.hpp"
#include "unit walk anim component.hpp"
#include "unit death anim component.hpp"
#include "tower firing anim component.hpp"
#include "unit exit distance component.hpp"
#include "common tower stats component.hpp"

using CompList = Utils::TypeList<
  Sound,
  UnitDir,
  Position,
  UnitPath,
  UnitStats,
  TowerShoot,
  SlowEffect,
  UnitSprite,
  TowerEffect,
  TowerTiming,
  TowerTarget,
  TurretTower,
  SplashTower,
  TowerSprites,
  PoisonEffect,
  TowerUpgrades,
  UnitWalkAnim,
  UnitDeathAnim,
  TowerFiringAnim,
  UnitExitDistance,
  CommonTowerStats
>;

#endif